### ISSUE TITLE
How do I create a custom template?

### ISSUE THREAD

**Issue by ukslim** [jdarling/jQuery.Survey#3]
Sorry if the issues system is the wrong way to ask - it's the only way I could see. I guess you could consider it a documentation bug :)

jQuery.Survey seems perfect for my purpose, and I can get it to do what I want if I edit jQuery.Survey.js and modify the templates.

I assume I should be able to modify the templates from my own script though. What's the right way to do that?

More broadly, I want to style the entity surrounding a radio button so that it's a big clickable square that changes colour when the button is selected. So I guess I want control over the templates so I can add a class to buttons, and to understand how to hook functions to changes so I can change the class when a radio button is selected.

Thanks!

**Comment by jdarling** [comment]
It's been a long time since I looked at this library, but did a little fiddling and code reading.  Hopefully this answers your question.

The templates for the controls are handlebars templates that are stored on the prototype of the instance or in the global templates option hash.

Basically to change a template would look something like this:

```
<html>
  <head>
  </head>
  <body>
    <h1>Your survey below</h1>
    <form>
      <fieldset id="survey">
      </fieldset>
    </form>
    <script type="text/javascript" src="jquery.js"></script>
    <script type="text/javascript" src="handlebars.js"></script>
    <script type="text/javascript" src="../jQuery.Survey.js"></script>
    <script type="text/javascript" src="jquery.validate.js"></script>
    <script type="text/javascript" src="survey.js"></script>
    <script type="text/javascript">
      var person = {};
      $(document).ready(function(){
        $('#survey').survey({
          survey: survey,
          data: person,
          init: function(target){
            target.closest('form').validate({
              errorPlacement: function(error, element){
                var p = element;
                while(p && (!p.hasClass('input'))){
                  p = p.parent();
                }
                error.appendTo(p||element);
              },
              wrapper: 'div'
            });
          },
          beforeChange: function(from, to, next){
            var target = this;
            if(from === void 0){
              next();
            }else if(target.closest('form').valid()){
              var survey = $.survey(target);
              var data = survey.pageData();
              var surveyData = survey.data();
              survey.updateData(data);
              next();
            }
          },
          templates: {
            customText: '<div><label>{{element.label}}</label>{{element.value}}</div>'
          }
        });
      });
    </script>
  </body>
</html>
```

Then to use it just add a customText element to your elements array, something like:

```
var survey = {
  title: 'signup',
  name: 'signup',
  pages: [
    {
      name: 'generalinfo',
      title: 'Signup',
      elements: [
        {
          name: "testText",
          type: 'customText',
          label: "Foo Bar Label: ",
          value: "foo bar",
          required: true
        },
        {
          name: "firstName",
          type: 'text',
          label: "First Name",
          placeholder: "Your First Name...",
          required: true
        },
 ...bla bla bla...
```

So to create your custom radio just follow something similar.  You can always override the radio template if you want all radio's to be your custom one.  I just used customText for giggles and grins.

**Comment by ukslim** [comment]
Thanks for spending the time on this.
